### ISSUE TITLE
Simulated data and spectral matching code are messing

### ISSUE THREAD

**Issue by DrSalemSalem** [BrandonSmithJ/band-adjustment#2]
Dear Smith,

Thank you for sharing the source code for Spectral Band Adjustments.
The paper with its source code is a very important source for spectral band adjustments.

The dropbox link to the simulated data used to train the networks is no longer valid.
In addition, the folder that includes "Rrs_LUT_%s" to train a new network is also missing.

Although the codes for DNN and QAA exist, I could not find the code to conduct spectral matching.

I hope you could guide me to find the answer to my inquiries.

Best regards
Salem

**Comment by BrandonSmithJ** [comment]
Thank you for pointing that out - I've updated the readme link to the simulated data (which directs to https://figshare.com/articles/dataset/Hyperspectral_Rrs_Spectra/5378650 ). The "Rrs_LUT_%s" files are the simulated data, resampled to the appropriate sensor wavelengths.  

Spectral matching, as described in the paper, is performed by selecting the simulated spectrum which minimizes RMSE with respect to the input (target) spectrum. This was conducted by a co-author and so the exact code isn't available, but it should be simple enough for you to create if you'd like to use the method elsewhere.

**Comment by DrSalemSalem** [comment]
Thank you for updating the simulated data. I could successfully download and read the data.
I would recommend adding the extension for the two files (i.e., csv) as it is missing.

As for the spectral matching code, I will create it.

Thanks again!
